db:
  image: db
  restart: always
  ports:
    - "5432"
redis:
  image: redis
  restart: always
  ports:
    - "6379"
memcached:
  image: memcached
  restart: always
  ports:
    - "11211"
sphinx:
  image: sphinx
  restart: always
  ports:
    - "9306"
    - "10809"
    - "22"
  links:
    - db
web:
  image: web
  restart: always
  ports:
    - "80"
  links:
    - db
    - redis
    - memcached
    - sphinx
