db:
  build: db
  restart: always
  ports:
    - "5432"
redis:
  build: redis
  restart: always
  ports:
    - "6379"
memcached:
  build: memcached
  restart: always
  ports:
    - "11211"
sphinx:
  build: sphinx
  restart: always
  ports:
    - "9306"
    - "10809"
  links:
    - db
